### ISSUE TITLE
TypeError: Cannot read property 'complete' of null

### ISSUE THREAD

**Issue by mrbernnz** [feross/webtorrent#1029]
**What version of WebTorrent?**
1.9.0 (0.98.3)
**What operating system and Node.js version?**
macOS Sierra (10.12.2)
7.4.0 (node)
**What browser and version? (if using WebTorrent in the browser)**
N/A
**What did you expect to happen?**
Just a completion print to screen
**What actually happened?**
```sh
UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/feross/webtorrent/issues

DEBUG INFO: webtorrent-cli 1.9.0, webtorrent 0.98.3, node v7.4.0, darwin x64, exit 1
/usr/local/lib/node_modules/webtorrent-cli/node_modules/webtorrent/lib/torrent.js:1537
        if (self._checkDone()) self.discovery.complete()
                                             ^

TypeError: Cannot read property 'complete' of null
    at /usr/local/lib/node_modules/webtorrent-cli/node_modules/webtorrent/lib/torrent.js:1537:46
    at /usr/local/lib/node_modules/webtorrent-cli/node_modules/simple-sha1/index.js:6:5
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by mrbernnz** [comment]
Sorry just made an identical issue to #1022

**Comment by feross** [comment]
No worries, thanks for the report.
