### ISSUE TITLE
"Error: Cannot add duplicate torrent" but webtorrent-desktop work.

### ISSUE THREAD

**Issue by VinceXie** [feross/webtorrent#1037]
**What version of WebTorrent?**
0.98.5
**What operating system and Node.js version?**
osx 10.12.2
**What browser and version? (if using WebTorrent in the browser)**

**What did you expect to happen?**
download file
**What actually happened?**
error but webtorrent-desktop work.

Magnet link:
---
magnet:?xt=urn:btih:D3FCB351B1B9C93144695D9042D88D5EC29CB8FB&dn=The+Last+Reef+3D+%282012%29+%5B720p%5D+%5BYTS.AG%5D&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337

Error infomation:
---
`DEBUG_FD` is deprecated. Override `debug.log` if you want to use a different log function (https://git.io/vMUyr)
Client is downloading: d3fcb351b1b9c93144695d9042d88d5ec29cb8fb
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Cannot add duplicate torrent d3fcb351b1b9c93144695d9042d88d5ec29cb8fb
    at Torrent.onInfoHash (/Users/vincexie/Desktop/tmp/VSpider/node_modules/webtorrent/index.js:272:26)
    at Torrent.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at Torrent.emit (events.js:182:7)
    at Torrent._onParsedTorrent (/Users/vincexie/Desktop/tmp/VSpider/node_modules/webtorrent/lib/torrent.js:265:8)
    at /Users/vincexie/Desktop/tmp/VSpider/node_modules/webtorrent/lib/torrent.js:232:12
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Here my code
---
```
/**
 * Created by vincexie on 2017/2/9.
 */
var WebTorrent = require('webtorrent')

var client = new WebTorrent()
var magnetURI = 'magnet:?xt=urn:btih:D3FCB351B1B9C93144695D9042D88D5EC29CB8FB&dn=The+Last+Reef+3D+%282012%29+%5B720p%5D+%5BYTS.AG%5D&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Fp4p.arenabg.ch%3A1337&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337'

client.add(magnetURI, function (torrent) {
  // Got torrent metadata!
  console.log('Client is downloading:', torrent.infoHash)

  client.add(magnetURI, { path: '../movies' }, function (torrent) {
    torrent.on('done', function () {
      console.log('torrent download finished')
    })
  })
})
```

**Comment by VinceXie** [comment]
i find my fault
