### ISSUE TITLE
Cannot read property 'complete' of null

### ISSUE THREAD

**Issue by kim0** [feross/webtorrent#1083]
**What version of WebTorrent?**
webtorrent 0.98.3
**What operating system and Node.js version?**
node v7.7.4, darwin x64
**What browser and version? (if using WebTorrent in the browser)**
n/a
**What did you expect to happen?**
exit successfully
**What actually happened?**
Crashed
```
webtorrent is exiting...

UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/feross/webtorrent/issues

DEBUG INFO: webtorrent-cli 1.9.0, webtorrent 0.98.3, node v7.7.4, darwin x64, exit 1
/usr/local/lib/node_modules/webtorrent-cli/node_modules/webtorrent/lib/torrent.js:1537
        if (self._checkDone()) self.discovery.complete()
                                             ^

TypeError: Cannot read property 'complete' of null
    at /usr/local/lib/node_modules/webtorrent-cli/node_modules/webtorrent/lib/torrent.js:1537:46
    at /usr/local/lib/node_modules/webtorrent-cli/node_modules/simple-sha1/index.js:6:5
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by feross** [comment]
You're running an old version of webtorrent. This bug was fixed in 0.98.4. Please upgrade to the latest version.
