### ISSUE TITLE
Seeding from node fails

### ISSUE THREAD

**Issue by cjb** [feross/webtorrent#294]
Seeding a file from node is failing here:
```js
var WebTorrent = require('webtorrent')
var client = new WebTorrent()
client.seed('myfile', function onTorrent (torrent) {
  console.log('Torrent info hash:', torrent.infoHash)
})
```
results in:
```
ReferenceError: WebSocket is not defined
    at Socket._init (/home/cjb/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/simple-websocket/index.js:44:18)
    at new Socket (/home/cjb/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/node_modules/simple-websocket/index.js:22:8)
    at new WebSocketTracker (/home/cjb/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/lib/websocket-tracker.js:36:49)
    at /home/cjb/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/client.js:66:16
    at Array.map (native)
    at new Client (/home/cjb/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/client.js:55:6)
    at Discovery._createTracker (/home/cjb/node_modules/webtorrent/node_modules/torrent-discovery/index.js:97:18)
    at Discovery.setTorrent (/home/cjb/node_modules/webtorrent/node_modules/torrent-discovery/index.js:58:10)
    at Torrent._onSwarmListening (/home/cjb/node_modules/webtorrent/lib/torrent.js:210:18)
    at Swarm.g (events.js:180:16)
```
(It's trying to use wss://tracker.webtorrent.io/)

Is it user error, or a bug?

**Comment by zajac** [comment]
+1. I see exactly the same problem.

**Comment by cjb** [comment]
@zajac `new WebTorrent({tracker: false})` works, by the way, though that doesn't help if you wanted to use a tracker.

**Comment by pldubouilh** [comment]
Same here, can't use `new WebTorrent()` without `{tracker: false}`

**Comment by feross** [comment]
Thanks for reporting. I'm preparing webtorrent to support connecting to browser peers with WebRTC, and I `npm publish`'d a few of the dependencies a bit early, namely `bittorrent-tracker`. I'll fix this up today!

**Comment by feross** [comment]
Okay, the reported crash should be fixed now. You can get the latest webtorrent dependencies by simply reinstalling:

```npm rm webtorrent && npm i webtorrent`

Or by updating all dependencies:

```npm update```

**Comment by feross** [comment]
So, the reported issue is fixed, but webtorrent will still crash if web peers are actually found from the webtorrent tracker. Admittedly, this is super rare, so you probably have nothing to worry about :)

There will be a complete fix once the hybrid client is done. It's really close. Last thing I need to do is merge `webtorrent-swarm` into `bittorrent-swarm` so webtorrent can just treat both types of peers the same and the complexity is handled in `bittorrent-swarm`. This is the last piece.

That's how `bittorrent-tracker` and `torrent-discovery` currently do it, and it's worked well so far :)

**Comment by cjb** [comment]
I saw this error the first time I tried seeding with webtorrent after updating version, haven't seen it again:
```
 λ node webtorrent.js
idHex a984c28c475372e3589ac8dc8bdd07a226c17cce

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write Unknown system errno 89
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
```

**Comment by cjb** [comment]
I haven't seen this again and I think I might have hit ctrl-c, so I'm gonna go ahead and close this issue.  I successfully seeded and downloaded using node with the new npm version.  Thanks!
