### ISSUE TITLE
Cannot read property 'wires' of null

### ISSUE THREAD

**Issue by Froren** [feross/webtorrent#324]
I've been able to run webtorrent with node on windows with a lot of success.

Recently I tried it on 2 different ubuntu servers (13.10 and 14.~), but I've been receiving these error messages and I'm not sure why:

    /var/pnode/node_modules/webtorrent/node_modules/bittorrent-swarm/lib/peer.js:184
      self.swarm.wires.splice(self.swarm.wires.indexOf(self.wire), 1)
                ^
    TypeError: Cannot read property 'wires' of null
        at Peer.destroy (/var/pnode/node_modules/webtorrent/node_modules/bittorrent-swarm/lib/peer.js:184:13)
        at Wire.destroy (/var/pnode/node_modules/webtorrent/node_modules/bittorrent-swarm/lib/peer.js:91:10)
        at Wire.g (events.js:175:14)
        at Wire.EventEmitter.emit (events.js:117:20)
        at finishMaybe (_stream_writable.js:352:12)
        at afterWrite (_stream_writable.js:272:5)
        at _stream_writable.js:259:9
        at process._tickCallback (node.js:415:13)

and

    /var/pnode/node_modules/webtorrent/node_modules/bittorrent-swarm/lib/peer.js:184
      self.swarm.wires.splice(self.swarm.wires.indexOf(self.wire), 1)
                ^
    TypeError: Cannot read property 'wires' of null
        at Peer.destroy (/var/pnode/node_modules/webtorrent/node_modules/bittorrent-swarm/lib/peer.js:184:13)
        at Timer.ontimeout (/var/pnode/node_modules/webtorrent/node_modules/bittorrent-swarm/lib/peer.js:171:57)

I've also seen a lot more ECONNRESET errors that didn't seem to show up when I was running it on Windows.. any ideas what could be causing this?

**Comment by feross** [comment]
Fixed in `bittorrent-swarm` 5.0.3. `webtorrent` should inherit the fix if you're running the latest version and you run `npm update`.
