### ISSUE TITLE
Seeding fails with an exception when no internet connection is available

### ISSUE THREAD

**Issue by jhiesey** [feross/webtorrent#366]
I don't expect it to work with no internet, but a more graceful failure would be nice.

```
$ webtorrent-hybrid seed mydir

ERROR: If you think this is a bug in webtorrent, report it!
=====>                                               <=====
=====>  https://github.com/feross/webtorrent/issues  <=====
=====>                                               <=====
/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/lib/websocket-tracker.js:49
  if (!self._socket.connected) {
                   ^
TypeError: Cannot read property 'connected' of null
    at WebSocketTracker.announce (/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/lib/websocket-tracker.js:49:20)
    at /usr/local/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/client.js:202:13
    at Array.forEach (native)
    at Client._announce (/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/client.js:201:18)
    at Client.complete (/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/node_modules/torrent-discovery/node_modules/bittorrent-tracker/client.js:181:8)
    at FSStorage.<anonymous> (/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/lib/torrent.js:302:56)
    at FSStorage.emit (events.js:129:20)
    at FSStorage.Storage._checkDone (/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/lib/storage.js:657:10)
    at FSStorage.Storage._onFileDone (/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/webtorrent/lib/storage.js:649:8)
    at File.emit (events.js:104:17)
```

**Comment by jhiesey** [comment]
Looks like I had an old version. Seems fine with the newest on npm
