### ISSUE TITLE
Webtorrent-hybrid randomly dies

### ISSUE THREAD

**Issue by KeizerDev** [feross/webtorrent#582]
```
UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/feross/webtorrent/issues

DEBUG INFO: webtorrent 0.72.2, node v0.10.25, linux x64, exit 1

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
root@MijnServer:~/test# 
```

**Comment by rom1504** [comment]
See https://github.com/feross/webtorrent-hybrid/issues/5

**Comment by DiegoRBaquero** [comment]
I feel that, until webtorrent-hybrid is moved to electron o uses a wrtc implementation that works, it's not worth discussing or trying to resolve issues about it.
