### ISSUE TITLE
Destroy functionality broken when torrent running

### ISSUE THREAD

**Issue by niieani** [feross/webtorrent#589]
It seems that destroying the torrent doesn't stop the DHT events from being emitted, resulting in actions on a destroyed torrent and an error thrown.
Running `torrent.destroy()` on a running torrent may cause the following error:

```
  if (self.destroyed) throw new Error('torrent is destroyed')
                      ^

Error: torrent is destroyed
    at Torrent.addPeer (/app/node_modules/webtorrent/lib/torrent.js:453:29)
    at emitOne (events.js:77:13)
    at Discovery.emit (events.js:169:7)
    at DHT.onPeer (/app/node_modules/torrent-discovery/index.js:66:10)
    at emitThree (events.js:102:20)
    at DHT.emit (events.js:175:7)
    at emit (/app/node_modules/bittorrent-dht/client.js:316:12)
    at onreply (/app/node_modules/bittorrent-dht/client.js:322:27)
    at onreply (/app/node_modules/bittorrent-dht/client.js:532:12)
    at Object.afterQuery [as callback] (/app/node_modules/k-rpc/index.js:272:18)
    at Socket.onmessage (/app/node_modules/k-rpc-socket/index.js:101:11)
    at emitTwo (events.js:87:13)
    at Socket.emit (events.js:172:7)
    at UDP.onMessage (dgram.js:480:8)
```

**Comment by feross** [comment]
Thanks for the issue. I think I figured out the source of the error. It's the new version of `bittorrent-dht`. It was completely rewritten to be much faster, but there's going to be a few kinks like this until it gets some more usage ;)

PR sent upstream.

**Comment by feross** [comment]
And just like that, it's fixed! Re-install webtorrent to get the fix.

**Comment by niieani** [comment]
Awesome, thanks!
