### ISSUE TITLE
Error in DHT's LRU module 

### ISSUE THREAD

**Issue by oleiba** [feross/webtorrent#592]
Hi, I'm deploying a bittorrent client on top on latest webtorrent version 0.72.2.
Use case: I'm seeding hundreds of files (each under 1MB), and after seeding ~500 files sequentially (which takes about an hour) I get this error:
`
/var/app/current/node_modules/cc-metadata-handler/node_modules/webtorrent/node_modules/bittorrent-dht/node_modules/lru/index.js:25
        if(element.prev) this.cache[element.prev].next = element.next;
                                                       ^
TypeError: Cannot set property 'next' of undefined
    at LRU.remove (/var/app/current/node_modules/cc-metadata-handler/node_modules/webtorrent/node_modules/bittorrent-dht/node_modules/lru/index.js:25:56)
    at LRU.get (/var/app/current/node_modules/cc-metadata-handler/node_modules/webtorrent/node_modules/bittorrent-dht/node_modules/lru/index.js:84:14)
    at DHT.announce (/var/app/current/node_modules/cc-metadata-handler/node_modules/webtorrent/node_modules/bittorrent-dht/client.js:259:28)
    at Discovery._dhtAnnounce (/var/app/current/node_modules/cc-metadata-handler/node_modules/webtorrent/node_modules/torrent-discovery/index.js:166:12)
    at null._onTimeout (/var/app/current/node_modules/cc-metadata-handler/node_modules/webtorrent/node_modules/torrent-discovery/index.js:176:10)
    at Timer.listOnTimeout (timers.js:119:15)
`

**Comment by feross** [comment]
Closing, since this is already being tracked here: https://github.com/feross/bittorrent-dht/pull/110.
