### ISSUE TITLE
throw new Error('Not running'); // error message from dgram_legacy.js

### ISSUE THREAD

**Issue by leidegre** [feross/webtorrent#601]
I don't got more atm but I'm getting this error soon after a torrent is removed, there's two in total, the other one is pending.

I have a working repo locally but it's not something I can reproduce elsewhere, the issue is probably external but there doesn't seem to be a way for me to handle the error, so the application crashes.

~~~
dgram.js:461
    throw new Error('Not running'); // error message from dgram_legacy.js

Error: Not running
    at Socket._healthCheck (dgram.js:461:11)
    at Socket.send (dgram.js:285:8)
    at RPC.send (C:\Projects\tordl\node_modules\k-rpc-socket\index.js:132:15)
    at RPC.query (C:\Projects\tordl\node_modules\k-rpc-socket\index.js:176:8)
    at RPC.query (C:\Projects\tordl\node_modules\k-rpc\index.js:142:17)
    at DHT._sendPing (C:\Projects\tordl\node_modules\bittorrent-dht\client.js:94:13)
    at DHT.addNode (C:\Projects\tordl\node_modules\bittorrent-dht\client.js:84:8)
    at Wire.<anonymous> (C:\Projects\tordl\node_modules\webtorrent\lib\torrent.js:582:23)
    at emitOne (events.js:90:13)
    at Wire.emit (events.js:182:7)
~~~

**Comment by feross** [comment]
- What version of `webtorrent` are you using?
- What version of node.js are you using?

cc @mafintosh

**Comment by leidegre** [comment]
@feross yeah, sorry. Latest 0.72.2 (first thing I did was to bump/update the version of webtorrent)

Latest node version, 5.5

**Comment by feross** [comment]
Can you reliably trigger this error? If you can share code that triggers it reliably, it would really help to debug the issue.

Also, please try using webtorrent 0.74.0, since behavior might have changed.

**Comment by feross** [comment]
Attempted a naive fix and released as v0.74.1.

Going to assume this is fixed now. If you see it again, please leave a comment here and I will re-open this issue.

**Comment by leidegre** [comment]
@feross I'll look into. I had a working repro with a couple of torrents. I'll see if I can put together something. I'll also check if the bug is there before or after your fix.

Thanks for this.

**Comment by leidegre** [comment]
No dice but a different stack trace.

dgram.js:461
    throw new Error('Not running'); // error message from dgram_legacy.js
    ^

Error: Not running
    at Socket._healthCheck (dgram.js:461:11)
    at Socket.address (dgram.js:371:8)
    at RPC.address (C:\Projects\tordl\node_modules\k-rpc-socket\index.js:119:22)
    at RPC.address (C:\Projects\tordl\node_modules\k-rpc\index.js:107:22)
    at DHT.address (C:\Projects\tordl\node_modules\bittorrent-dht\client.js:330:20)
    at Torrent._onWire (C:\Projects\tordl\node_modules\webtorrent\lib\torrent.js:585:31)
    at emitTwo (events.js:92:20)
    at Swarm.emit (events.js:172:7)
    at Peer.onHandshake (C:\Projects\tordl\node_modules\bittorrent-swarm\lib\peer.js:189:14)
    at Wire.<anonymous> (C:\Projects\tordl\node_modules\bittorrent-swarm\lib\peer.js:136:10)

**Comment by feross** [comment]
This was probably fixed a while ago. There were lots of fixes of this sort in `bittorrent-dht` a while ago.
