### ISSUE TITLE
Object prototype may only be an object or null

### ISSUE THREAD

**Issue by kulyzu** [feross/webtorrent#616]
util.js:556
  ctor.prototype = Object.create(superCtor.prototype, {
                          ^
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at exports.inherits (util.js:556:27)
    at Object.<anonymous> (/home/username/.node_modules/lib/node_modules/webtorrent/node_modules/render-media/node_modules/videostream/mp4-remuxer.js:20:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/username/.node_modules/lib/node_modules/webtorrent/node_modules/render-media/node_modules/videostream/videostream.js:6:18)

[1]+  Exit 8                  webtorrent magnet:?xt=urn:btih:73A3E1F9492BA6B0FA5AFB95FEEBA59C001ABF62

what i did is
`webtorrent magnet_link`

**Comment by kulyzu** [comment]
This is not an issue, sorry i was using an old node version.

after i installed the latest, i reinstall webtorrent, but now it stuck on fetching torrent metadata from 0 peers and then it exit.

am using the command as above

**Comment by feross** [comment]
Don't use WebTorrent for piracy. We cannot help with such requests.
