### ISSUE TITLE
Sometimes addPeer is still triggered after webtorrent.remove(torrentId)

### ISSUE THREAD

**Issue by niieani** [feross/webtorrent#623]
Do this repeatedly and you'll eventually see the problem:

```js
const parsedTorrent = {...}; // ParsedTorrent from ParseTorrent
webTorrent.add(parsedTorrent, { path: ... }, (torrent) => {
  webTorrent.remove(torrent.infoHash);
});
```

Seems like internally a DHT scheduled a connection to be created before the torrent was destroyed is still trying to add a peer even after (or during) the time it was removed.

Looks like a possible regression of this https://github.com/feross/webtorrent/issues/589.

Error:
```js
/Users/nixin/Documents/Projects/webtorrent/lib/torrent.js:456
  if (self.destroyed) throw new Error('torrent is destroyed')
                      ^
Error: torrent is destroyed
    at Torrent.addPeer (/Users/nixin/Documents/Projects/webtorrent/lib/torrent.js:456:29)
    at emitOne (events.js:90:13)
    at Discovery.emit (events.js:182:7)
    at DHT.onPeer (/Users/nixin/Documents/Projects/webtorrent/node_modules/torrent-discovery/index.js:66:10)
    at emitThree (events.js:115:20)
    at DHT.emit (events.js:188:7)
    at emit (/Users/nixin/Documents/Projects/webtorrent/node_modules/bittorrent-dht/client.js:316:12)
    at onreply (/Users/nixin/Documents/Projects/webtorrent/node_modules/bittorrent-dht/client.js:322:27)
    at onreply (/Users/nixin/Documents/Projects/webtorrent/node_modules/bittorrent-dht/client.js:532:12)
    at Object.afterQuery [as callback] (/Users/nixin/Documents/Projects/webtorrent/node_modules/k-rpc/index.js:272:18)
    at Socket.onmessage (/Users/nixin/Documents/Projects/webtorrent/node_modules/k-rpc-socket/index.js:101:11)
    at emitTwo (events.js:100:13)
    at Socket.emit (events.js:185:7)
    at UDP.onMessage (dgram.js:481:8)
```

**Comment by capric8416** [comment]
I edit file node_modules/webtorrent/lib/torrent.js at 707 line to skip this.
![image](https://cloud.githubusercontent.com/assets/7124338/16561995/b7dd75c8-41c1-11e6-8da4-5f9838a0ee92.png)

**Comment by capric8416** [comment]
I edit file node_modules/webtorrent/lib/torrent.js at line 707 to skip this.
![image](https://cloud.githubusercontent.com/assets/7124338/16562240/15c36e7c-41c2-11e6-9e6e-60c619a1ba0c.png)

**Comment by feross** [comment]
@niieani @capric8416 This issue should be fixed in the latest version of `webtorrent`.

@capric8416 Can you check what version of webtorrent you have installed?
