### ISSUE TITLE
peer._destroy is not a function On torrent.pause()

### ISSUE THREAD

**Issue by Lunik** [feross/webtorrent#784]
* WebTorrent version:
0.91.2
* Node.js version:
5.11.0

I get this issues when I'm pausing the client before destroy him:
```
/home/lunik/torrent/node_modules/webtorrent/lib/torrent.js:716
  if (self.paused) return peer._destroy(new Error('torrent is paused'))
                               ^

TypeError: peer._destroy is not a function
    at Torrent._addIncomingPeer (/home/lunik/torrent/node_modules/webtorrent/lib/torrent.js:716:32)
    at Wire.onHandshake (/home/lunik/torrent/node_modules/webtorrent/lib/tcp-pool.js:109:15)
    at Wire.g (events.js:273:16)
    at emitThree (events.js:115:20)
    at Wire.emit (events.js:188:7)
    at Wire._onHandshake (/home/lunik/torrent/node_modules/bittorrent-protocol/index.js:434:8)
    at Wire._parser (/home/lunik/torrent/node_modules/bittorrent-protocol/index.js:700:12)
    at Wire._write (/home/lunik/torrent/node_modules/bittorrent-protocol/index.js:591:10)
    at doWrite (/home/lunik/torrent/node_modules/bittorrent-protocol/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/home/lunik/torrent/node_modules/bittorrent-protocol/node_modules/readable-stream/lib/_stream_writable.js:302:5)
```

```
function stop(client) {
  if (client.torrent) {
    client.torrent.pause()
    setTimeout(function () {
      client.torrent.destroy()
    }, 1000)
  }
}
```

**Comment by feross** [comment]
Fixed in 0.91.4
