### ISSUE TITLE
If there is a parsing error, We were unable to locate which torrent error.

### ISSUE THREAD

**Issue by starzou** [feross/webtorrent#840]
* WebTorrent version: 0.94.4
* Node.js : 6.2.0

In https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L235
```js
Torrent.prototype._onTorrentId = function (torrentId) {
  var self = this
  if (self.destroyed) return

  var parsedTorrent
  try { parsedTorrent = parseTorrent(torrentId) } catch (err) {}
  if (parsedTorrent) {
    // Attempt to set infoHash property synchronously
    self.infoHash = parsedTorrent.infoHash
    process.nextTick(function () {
      if (self.destroyed) return
      self._onParsedTorrent(parsedTorrent)
    })
  } else {
    // If torrentId failed to parse, it could be in a form that requires an async
    // operation, i.e. http/https link, filesystem path, or Blob.
    parseTorrent.remote(torrentId, function (err, parsedTorrent) {
      if (self.destroyed) return
      if (err) return self._destroy(err)
      self._onParsedTorrent(parsedTorrent)
    })
  }
}
```

In https://github.com/feross/webtorrent/blob/master/lib/torrent.js#L679
``` js
  if (err) {
    // Torrent errors are emitted at `torrent.on('error')`. If there are no 'error' event
    // handlers on the torrent instance, the error will be emitted at
    // `client.on('error')`. This prevents crashing the user's program, but it makes it
    // impossible to determine a client error versus a torrent error (where the client
    // is still usable afterwards). Users are recommended for errors in both places
    // to distinguish between the error types.
    if (self.listenerCount('error') === 0) {
      self.client.emit('error', err)
    } else {
      self.emit('error', err)
    }
  }
```

### We code:
``` js
const WebTorrent = require('webtorrent');

const client = new WebTorrent();

const torrentId = 'not-found';

client.add(torrentId, function (torrent) {

});

client.on('error', function (err) {
  console.error(err);
});

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Invalid torrent identifier
    at ReadFileContext.callback (/project/node_modules/parse-torrent/index.js:78:26)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
```

### So,  we need provide torrentId argument.

```js

if (err) {
  // Torrent errors are emitted at `torrent.on('error')`. If there are no 'error' event
  // handlers on the torrent instance, the error will be emitted at
  // `client.on('error')`. This prevents crashing the user's program, but it makes it
  // impossible to determine a client error versus a torrent error (where the client
  // is still usable afterwards). Users are recommended for errors in both places
  // to distinguish between the error types.
  if (self.listenerCount('error') != 0) {
    self.emit('error', err, torrentId);
  } else if (self.client.listenerCount('error') != 0) {
    self.client.emit('error', err, torrentId);
  } else {
    process.emit('error', err, torrentId);
  }
}
```

**Comment by starzou** [comment]
@feross what do you think?

**Comment by feross** [comment]
If there is a parsing error, you can locate which torrent is responsible using `torrent.on('error')`

```
var torrent = client.add(torrentId, function (torrent) {

});

torrent.on('error', function (err) {
  console.error(err);
});
```

The `client.add` call actually returns the `torrent` object right away, even though it's also passed into the callback.
