### ISSUE TITLE
TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#920]
* WebTorrent version: 0.97.0
* Node.js version: Electron 1.3.4

Noticed this error in the wild from WebTorrent Desktop:

```
Processes: webtorrent, platforms: darwin linux win32, versions: 0.13.1 0.14.0 0.15.0
TypeError: Cannot read property 'start' of undefined
    at onReady (.../node_modules/webtorrent/lib/server.js:123:27)
    at Server.onRequest (.../node_modules/webtorrent/lib/server.js:77:7)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
```

**Comment by feross** [comment]
PR sent: #921
