### ISSUE TITLE
Error: torrent is destroyed

### ISSUE THREAD

**Issue by feross** [feross/webtorrent#922]
- WebTorrent version: 0.97.0
- Node.js version: Electron 1.3.5

More instances of the famous "Error: torrent is destroyed" error, even though we just fixed one in 0.97.0.

It's funny -- we could actually get rid of all these by just returning instead of throwing an exception, but throwing helps us find all these cases where we didn't do proper cleanup and stuff is still happening after the torrent is destroyed.

```
Processes: webtorrent, platforms: darwin linux win32, versions: pre-0.12 0.13.1 0.14.0 0.15.0
Error: torrent is destroyed
    at Torrent.critical (...\node_modules\webtorrent\lib\torrent.js:895:29)
    at FileStream._notify (...\node_modules\webtorrent\lib\file-stream.js:53:26)
    at FileStream._read (...\node_modules\webtorrent\lib\file-stream.js:45:8)
    at FileStream.Readable.read (...\node_modules\webtorrent\node_modules\readable-stream\lib\_stream_readable.js:361:10)
    at readableAddChunk (...\node_modules\webtorrent\node_modules\readable-stream\lib\_stream_readable.js:214:18)
    at FileStream.Readable.push (...\node_modules\webtorrent\node_modules\readable-stream\lib\_stream_readable.js:172:10)
    at ...\node_modules\webtorrent\lib\file-stream.js:78:10
    at ...\node_modules\fs-chunk-store\index.js:200:7
    at end (...\node_modules\run-parallel\index.js:16:15)
    at done (...\node_modules\run-parallel\index.js:20:10)
```

**Comment by DiegoRBaquero** [comment]
Should have been fixed with https://github.com/feross/webtorrent/commit/6d5ff7ab06541847f86819825fe229516148b26e

**Comment by feross** [comment]
Alright, let's close this. I'll keep an eye on the WebTorrent Desktop telemetry for v0.18.0 and re-open if this error is still present.
