### ISSUE TITLE
Unexpected error while streaming

### ISSUE THREAD

**Issue by Ninitage** [feross/webtorrent#986]
First, thanks for your work here, that's really great!

* webtorrent-cli 1.8.0
* webtorrent 0.98.0
* node v7.0.0

Got an unexpected error while downloading and streaming, so it stopped completely each time I tried, and told me this:

-------------------------------------------------------------------

DEBUG INFO: webtorrent-cli 1.8.0, webtorrent 0.98.0, node v7.0.0, darwin x64, exit 1
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: SUBSCRIBE renewal error
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/upnp-device-client/index.js:234:25)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)

---------------------------------------------------------

Any ideas?

**Comment by feross** [comment]
This looks like an error in the `dlnacasts` package. Can you open an issue on @grunjol's repository here: https://github.com/grunjol/dlnacasts
