### ISSUE TITLE
Error: Invalid data: Missing delimiter ":" [0x3a]

### ISSUE THREAD

**Issue by ibocon** [feross/webtorrent#995]
**Hardware**: Raspberry Pi 2  
**Operating System**: Ubuntu 16.04 LTS  
**Nodejs**: v6.9.2  
**WebTorrent**: v1.0.5
**Aplication**: MEAN stack   
**Source Code**: https://github.com/ibocon/project-Myblog

I am trying to download video by using Web-Torrent.

My code is working perfectly on Windows 7.
However, my code does not working when I run on Ubuntu.

This is error stack,

    /home/gun/project-Myblog/animation/src/update.js:168
            if(err) throw err;
                    ^
    
    Error: Invalid data: Missing delimiter ":" [0x3a]
        at Function.decode.find (/home/gun/project-Myblog/animation/node_modules/bencode/lib/decode.js:61:9)
        at Function.decode.buffer (/home/gun/project-Myblog/animation/node_modules/bencode/lib/decode.js:106:20)
        at Function.decode.dictionary (/home/gun/project-Myblog/animation/node_modules/bencode/lib/decode.js:74:17)
        at Function.decode.next (/home/gun/project-Myblog/animation/node_modules/bencode/lib/decode.js:41:21)
        at Function.decode.dictionary (/home/gun/project-Myblog/animation/node_modules/bencode/lib/decode.js:74:36)
        at Function.decode.next (/home/gun/project-Myblog/animation/node_modules/bencode/lib/decode.js:41:21)
        at Object.decode (/home/gun/project-Myblog/animation/node_modules/bencode/lib/decode.js:30:17)
        at decodeTorrentFile (/home/gun/project-Myblog/animation/node_modules/parse-torrent-file/index.js:17:23)
        at parseTorrent (/home/gun/project-Myblog/animation/node_modules/parse-torrent/index.js:32:12)
        at parseOrThrow (/home/gun/project-Myblog/animation/node_modules/parse-torrent/index.js:89:23)
        at /home/gun/project-Myblog/animation/node_modules/parse-torrent/index.js:79:7
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

I guess my code does not matter. Because it works on Windows 7.
Thus, I have no idea why it does not working on Ubuntu.

**Comment by feross** [comment]
I'm closing this issue because it's been a while without a response from the issue opener. It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.

**Comment by tobq** [comment]
Just ran into this issue.. I'm not on an ARM CPU, and am running the latest version of node.
