### ISSUE TITLE
UNEXPECTED ERROR DEBIAN 

### ISSUE THREAD

**Issue by ziomik** [feross/webtorrent#998]
DEBUG INFO: webtorrent-cli 1.8.1, webtorrent 0.98.0, node v4.7.0, linux ia32, exit 1
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: electron-eval error: Electron process exited with code 127.
Stderr:
/usr/lib/node_modules/webtorrent-hybrid/node_modules/electron-webrtc/node_modules/electron-eval/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

    at ChildProcess.<anonymous> (/usr/lib/node_modules/webtorrent-hybrid/node_modules/electron-webrtc/node_modules/electron-eval/lib/index.js:174:22)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:854:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)

**Comment by ziomik** [comment]
Solution: apt-get install libgconf-2-4
